services:
  db:
    image: postgres:14
    container_name: delphi-db
    environment:
      POSTGRES_PASSWORD: delphi
      POSTGRES_USER: delphi
      POSTGRES_DB: delphi
      PORT: 5432
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - delphi:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # for some reason this can't be mounted on first run
      - ./db/postgresql.conf:/etc/postgresql/data/postgresql.conf

volumes:
  delphi: